name: Deploy to S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync files to S3 bucket
        run: aws s3 sync . s3://awsresumebucket --exclude ".git/*" --exclude ".github/*" --exclude README.md --exact-timestamps

      - name: Clear CloudFront cache
        if: steps.deploy.outputs.changed == 'true'
        run: aws cloudfront create-invalidation --distribution-id EA4BC67IOZ71G --paths "/*"
